apiVersion: v2
name: quay
description: Red Hat Quay Registry Resources
type: application
version: 0.1.2
appVersion: "3.9"
home: https://github.com/validatedpatterns/quay-chart
maintainers:
  - name: Zero Trust Validated Patterns Team
    email: ztvp-arch-group@redhat.com
